'use client';
import {Canvas,useFrame} from '@react-three/fiber';
import {OrbitControls,Environment,Float,Html,ContactShadows} from '@react-three/drei';
import {useMemo,useRef,useState} from 'react';
import * as THREE from 'three';
function Mochi({onPet}){const g=useRef(),tail=useRef(),[happy,setHappy]=useState(false);useFrame((s)=>{if(g.current){g.current.position.y=.12+Math.sin(s.clock.elapsedTime*2)*.025;g.current.rotation.z=Math.sin(s.clock.elapsedTime*.7)*.025}if(tail.current)tail.current.rotation.z=.55+Math.sin(s.clock.elapsedTime*6)*.35});return <group ref={g} position={[0,.35,0]} onClick={(e)=>{e.stopPropagation();setHappy(true);onPet?.();setTimeout(()=>setHappy(false),1200)}}><mesh position={[0,.7,0]} castShadow><sphereGeometry args={[.72,32,24]}/><meshStandardMaterial color='#c98b5b' roughness={.72}/></mesh><mesh position={[0,.05,.05]} scale={[.82,.72,.9]} castShadow><sphereGeometry args={[.9,32,24]}/><meshStandardMaterial color='#dca36f' roughness={.8}/></mesh>{[-.42,.42].map((x,i)=><mesh key={i} position={[x,1.28,.05]} rotation={[0,0,i?-.35:.35]} castShadow><capsuleGeometry args={[.17,.5,8,16]}/><meshStandardMaterial color='#9b613f'/></mesh>)}{[-.25,.25].map(x=><mesh key={x} position={[x,.78,.65]}><sphereGeometry args={[.075,16,12]}/><meshStandardMaterial color='#211711'/></mesh>)}<mesh position={[0,.57,.72]}><sphereGeometry args={[.09,16,12]}/><meshStandardMaterial color='#342019'/></mesh><group ref={tail} position={[.75,.22,0]} rotation={[0,0,.55]}><mesh position={[.28,0,0]} rotation={[0,0,1.2]}><capsuleGeometry args={[.1,.55,8,12]}/><meshStandardMaterial color='#c98b5b'/></mesh></group>{happy&&<Html position={[0,1.8,0]} center><div className='heart'>♥ ♥</div></Html>}</group>}
function Decor({mode}){const [edit,setEdit]=useState(false);const [items,setItems]=useState([{id:'bed',p:[-1.7,.12,-.7],c:'#7c9a7e'},{id:'rug',p:[0,.025,-.8],c:'#d9b67e'},{id:'lamp',p:[1.7,.45,-.6],c:'#f3cf76'}]);return <group>{items.map((it,i)=><group key={it.id} position={it.p} onClick={(e)=>{if(mode==='room'){e.stopPropagation();setEdit(!edit)}}>{it.id==='rug'?<mesh rotation={[-Math.PI/2,0,0]}><circleGeometry args={[.72,32]}/><meshStandardMaterial color={it.c}/></mesh>:<><mesh castShadow><boxGeometry args={[it.id==='bed'?1:.32,it.id==='bed'?.28:1,it.id==='bed'?.7:.32]}/><meshStandardMaterial color={it.c}/></mesh>{it.id==='lamp'&&<pointLight position={[0,.5,0]} intensity={1.4} distance={3} color='#ffd59a'/>}</>}</group>)}{mode==='room'&&<Html position={[0,2.6,0]} center><button className='edit3d' onClick={()=>setEdit(!edit)}>{edit?'Done editing':'Edit decor'}</button></Html>}{edit&&<Html position={[0,2.15,0]} center><div className='editTip'>Tap furniture to select it. Full drag placement can be added with saved room layouts next.</div></Html>}</group>}
function Room({mode,onPet,onEvent}){const hour=new Date(new Date().toLocaleString('en-US',{timeZone:'Asia/Kolkata'})).getHours();const night=hour>=19||hour<6;const bg=night?'#101b30':hour>=17?'#e7a16c':'#b9d9ef';return <Canvas shadows camera={{position:[4,3.2,5],fov:48}} gl={{antialias:true}}><color attach='background' args={[bg]}/><ambientLight intensity={night?.35:.7}/><directionalLight position={[-3,5,3]} intensity={night?.25:2} castShadow/><Environment preset={night?'night':'sunset'}/><mesh rotation={[-Math.PI/2,0,0]} receiveShadow><planeGeometry args={[9,9]}/><meshStandardMaterial color={night?'#3b2b26':'#9d6e4b'} roughness={.9}/></mesh><mesh position={[0,2,-2.8]}><boxGeometry args={[7,4,.18]}/><meshStandardMaterial color={night?'#26324a':'#eadcc8'}/></mesh><mesh position={[0,2.3,-2.68]}><planeGeometry args={[2.2,1.35]}/><meshStandardMaterial color={night?'#172039':'#9ed0ee'} emissive={night?'#1d3158':'#000000'} emissiveIntensity={night?.7:0}/></mesh>{night&&<pointLight position={[0,2,-1.8]} color='#8ab5ff' intensity={1.2} distance={5}/>}<Float speed={1.2} rotationIntensity={.08} floatIntensity={.12}><Mochi onPet={()=>{onPet?.();onEvent?.('Mochi melted into happy little tail wags.')}}/></Float><Decor mode={mode}/><ContactShadows position={[0,0,0]} opacity={.35} scale={7} blur={2.5}/><OrbitControls makeDefault enablePan={false} minDistance={3} maxDistance={8} maxPolarAngle={Math.PI/2.05}/></Canvas>}
export default function Scene(p){return <Room {...p}/>}
