'use client';
import {Canvas,useFrame} from '@react-three/fiber';
import {OrbitControls,Environment,Float,Html,ContactShadows,Stars} from '@react-three/drei';
import {useRef,useState,useMemo} from 'react';
import * as THREE from 'three';
function Mochi({onPet}){const g=useRef(),tail=useRef(),head=useRef(),[happy,setHappy]=useState(false);useFrame((s)=>{let t=s.clock.elapsedTime;if(g.current){g.current.position.y=.18+Math.sin(t*2)*.035;g.current.rotation.z=Math.sin(t*.8)*.025}if(head.current)head.current.rotation.y=Math.sin(t*.55)*.12;if(tail.current)tail.current.rotation.z=.55+Math.sin(t*7)*.42});return <group ref={g} position={[0,.35,0]} onClick={e=>{e.stopPropagation();setHappy(true);onPet?.();setTimeout(()=>setHappy(false),1300)}}><group ref={head}><mesh position={[0,.78,0]} castShadow><sphereGeometry args={[.74,40,32]}/><meshStandardMaterial color='#c98b5b' roughness={.66}/></mesh>{[-.43,.43].map((x,i)=><mesh key={i} position={[x,1.3,.02]} rotation={[0,0,i?-.42:.42]} castShadow><capsuleGeometry args={[.18,.55,10,20]}/><meshStandardMaterial color='#92563a' roughness={.78}/></mesh>)}{[-.25,.25].map(x=><mesh key={x} position={[x,.8,.67]}><sphereGeometry args={[.078,20,16]}/><meshStandardMaterial color='#211711' roughness={.3}/></mesh>)}<mesh position={[0,.57,.73]}><sphereGeometry args={[.1,20,16]}/><meshStandardMaterial color='#342019'/></mesh><mesh position={[0,.45,.69]} scale={[.22,.08,.06]}><sphereGeometry args={[1,20,12]}/><meshStandardMaterial color='#39231b'/></mesh></group><mesh position={[0,.08,.03]} scale={[.85,.7,.92]} castShadow><sphereGeometry args={[.92,40,28]}/><meshStandardMaterial color='#dfa36f' roughness={.75}/></mesh>{[-.42,.42].map(x=><mesh key={x} position={[x,-.38,.42]} scale={[.28,.18,.35]} castShadow><sphereGeometry args={[1,20,16]}/><meshStandardMaterial color='#b97850'/></mesh>)}<group ref={tail} position={[.78,.18,-.05]} rotation={[0,0,.55]}><mesh position={[.3,0,0]} rotation={[0,0,1.2]}><capsuleGeometry args={[.11,.6,10,16]}/><meshStandardMaterial color='#c98b5b'/></mesh></group>{happy&&<Html position={[0,1.9,0]} center><div className='heart'>♥ ♥ ♥</div></Html>}</group>}
function Plant(){return <group><mesh position={[0,.45,0]}><cylinderGeometry args={[.24,.3,.55,16]}/><meshStandardMaterial color='#d49a62'/></mesh>{[-.25,0,.25].map((x,i)=><mesh key={i} position={[x,.95,0]} rotation={[0,0,x*1.2]}><sphereGeometry args={[.25,16,12]}/><meshStandardMaterial color='#6f9a72'/></mesh>)}</group>}
function Bed(){return <group><mesh position={[0,.2,0]}><boxGeometry args={[1.35,.32,.9]}/><meshStandardMaterial color='#7f9c8b'/></mesh><mesh position={[0,.38,.08]} scale={[.58,.12,.34]}><sphereGeometry args={[1,24,16]}/><meshStandardMaterial color='#f1e2c8'/></mesh></group>}
function Lamp(){return <group><mesh position={[0,.75,0]}><cylinderGeometry args={[.04,.04,1.4,12]}/><meshStandardMaterial color='#a77751' metallic={.15}/></mesh><mesh position={[0,1.48,0]}><coneGeometry args={[.34,.4,20,1,true]}/><meshStandardMaterial color='#f1cf82' side={THREE.DoubleSide}/></mesh><pointLight position={[0,1.35,0]} color='#ffd59a' intensity={1.8} distance={4}/></group>}
const initial=[{id:'bed',kind:'bed',p:[-1.65,.05,-.7],r:0},{id:'rug',kind:'rug',p:[0,.02,-.8],r:0},{id:'lamp',kind:'lamp',p:[1.7,.05,-.7],r:0},{id:'plant',kind:'plant',p:[-2.4,.05,-2],r:0}];
function Decor({mode}){const[items,setItems]=useState(initial),[edit,setEdit]=useState(false),[selected,setSelected]=useState(null);const move=(id,dx,dz)=>setItems(a=>a.map(x=>x.id===id?{...x,p:[Math.max(-3,Math.min(3,x.p[0]+dx)),x.p[1],Math.max(-2.3,Math.min(1.8,x.p[2]+dz))]}:x));const add=kind=>{let id=kind+Date.now();setItems(a=>[...a,{id,kind,p:[(Math.random()-.5)*4,.05,(Math.random()-.5)*2],r:0}])};return <>{items.map(it=><group key={it.id} position={it.p} rotation={[0,it.r,0]} onClick={e=>{if(mode==='room'){e.stopPropagation();setSelected(it.id);setEdit(true)}}}>{it.kind==='bed'?<Bed/>:it.kind==='lamp'?<Lamp/>:it.kind==='plant'?<Plant/>:<mesh rotation={[-Math.PI/2,0,0]}><circleGeometry args={[.8,40]}/><meshStandardMaterial color='#d8b47c' roughness={.9}/></mesh>}{selected===it.id&&<mesh position={[0,.03,0]} rotation={[-Math.PI/2,0,0]}><ringGeometry args={[.8,.86,32]}/><meshBasicMaterial color='#fff2c7'/></mesh>}</group>)}{mode==='room'&&<Html position={[0,2.55,0]} center><div className='editor3d'><button onClick={()=>setEdit(!edit)}>{edit?'✓ Done':'✦ Edit room'}</button>{edit&&<><button onClick={()=>add('plant')}>🪴</button><button onClick={()=>add('bed')}>🛏️</button><button onClick={()=>add('lamp')}>💡</button><button onClick={()=>add('rug')}>🟤</button>{selected&&<div className='editrow'><button onClick={()=>move(selected,-.35,0)}>←</button><button onClick={()=>move(selected,.35,0)}>→</button><button onClick={()=>move(selected,0,-.35)}>↑</button><button onClick={()=>move(selected,0,.35)}>↓</button><button onClick={()=>setItems(a=>a.map(x=>x.id===selected?{...x,r:x.r+Math.PI/4}:x))}>↻</button></div>}</>}</div></Html>}</>}
function WindowScene({night}){return <>{<mesh position={[0,2.35,-2.68]}><planeGeometry args={[2.2,1.35]}/><meshStandardMaterial color={night?'#172039':'#9ed0ee'} emissive={night?'#27436e':'#7db9d8'} emissiveIntensity={night?.7:.12}/></mesh>}<mesh position={[0,2.35,-2.66]}><boxGeometry args={[.08,1.45,.05]}/><meshStandardMaterial color='#f4ead8'/></mesh><mesh position={[0,2.35,-2.65]}><boxGeometry args={[2.3,.08,.05]}/><meshStandardMaterial color='#f4ead8'/></mesh></>}
function FoodBowl({food,onDone}){const[active,setActive]=useState(false);useFrame((_,d)=>{if(active)setTimeout(()=>{},0)});if(!food)return null;return <group position={[.95,.1,.65]}><mesh><cylinderGeometry args={[.38,.27,.22,24]}/><meshStandardMaterial color='#e5d2b7'/></mesh><mesh position={[0,.13,0]}><sphereGeometry args={[.2,16,12]}/><meshStandardMaterial color={food==='chicken'?'#c9794c':food==='apple'?'#bd4b45':'#7b5637'}/></mesh></group>}
function Room({mode,onPet,onEvent,food='kibble'}){const hour=Number(new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Kolkata',hour:'2-digit',hour12:false}).format(new Date()));const night=hour>=19||hour<6;const evening=hour>=17&&hour<19;const bg=night?'#0d1830':evening?'#d88660':hour<10?'#cfe5e8':'#b9d9ef';return <Canvas shadows dpr={[1,1.6]} camera={{position:[4.2,3.1,5.4],fov:48}} gl={{antialias:true,powerPreference:'high-performance'}}><color attach='background' args={[bg]}/>{night&&<Stars radius={20} depth={12} count={400} factor={2} fade speed={.4}/>}<ambientLight intensity={night?.28:.7}/><directionalLight position={[-3,5,3]} intensity={night?.35:evening?1.4:2.2} color={evening?'#ffb06f':'#fff2d0'} castShadow/><Environment preset={night?'night':evening?'sunset':'city'}/><mesh rotation={[-Math.PI/2,0,0]} receiveShadow><planeGeometry args={[9,9]}/><meshStandardMaterial color={night?'#3b2b26':'#9d6e4b'} roughness={.88}/></mesh><mesh position={[0,2,-2.8]}><boxGeometry args={[7,4,.18]}/><meshStandardMaterial color={night?'#26324a':'#eadcc8'} roughness={.95}/></mesh><WindowScene night={night}/>{night&&<pointLight position={[0,2,-1.8]} color='#8ab5ff' intensity={1.1} distance={5}/>}<Float speed={1.1} rotationIntensity={.06} floatIntensity={.09}><Mochi onPet={()=>{onPet?.();onEvent?.('Mochi accepted the pets and is now suspiciously pleased with himself.')}}/></Float><FoodBowl food={food}/><Decor mode={mode}/><ContactShadows position={[0,0,0]} opacity={.42} scale={7} blur={2.5}/><OrbitControls makeDefault enablePan={false} minDistance={3.2} maxDistance={8.2} minPolarAngle={.55} maxPolarAngle={Math.PI/2.02} enableDamping dampingFactor={.08}/></Canvas>}
export default function Scene(p){return <Room {...p}/>}
